################################################################################
#   CONFIGURATIONS FOR FITTING FaIR
################################################################################

# DATASET
dataset:
  # Path to data directory
  dirpath: data/

  # Keys of scenarios to load (for evaluation only)
  keys:
    - historical
    - ssp126
    - ssp245
    - ssp370
    #- ssp585



response_var: pr

# MODEL SPECIFICATIONS
model:



# TRAINING
training:

# EVALUATION
evaluation:
